export const Apis = [
  ["Animals", "animals"],
  ["Anime", "anime"],
  ["Anti-Malware", "antimalware"],
  ["Art & Design", "artanddesign"],
  ["Authentication & Authorization", "authenticationandauthorization"],
  ["Blockchain", "blockchain"],
  ["Books", "books"],
  ["Business", "business"],
  ["Calendar", "calendar"],
  ["Cloud Storage & File Sharing", "cloudstorageandfilesharing"],
  ["Continuous Integration", "continuousintegration"],
  ["Cryptocurrency", "cryptocurrency"],
  ["Currency Exchange", "currencyexchange"],
  ["Data Validation", "datavalidation"],
  ["Development", "development"],
  ["Dictionaries", "dictionaries"],
  ["Documents & Productivity", "documentsandproductivity"],
  ["Email", "email"],
  ["Entertainment", "entertainment"],
  ["Environment", "environment"],
  ["Events", "events"],
  ["Finance", "finance"],
  ["Food & Drink", "foodanddrink"],
  ["Games & Comics", "gamesandcomics"],
  ["Geocoding", "geocoding"],
  ["Government", "government"],
  ["Health", "health"],
  ["Jobs", "jobs"],
  ["Machine Learning", "machinelearning"],
  ["Music", "music"],
  ["News", "news"],
  ["Open Data", "opendata"],
  ["Open Source Projects", "opensourceprojects"],
  ["Patent", "patent"],
  ["Personality", "personality"],
  ["Phone", "phone"],
  ["Photography", "photography"],
  ["Programming", "programming"],
  ["Science & Math", "scienceandmath"],
  ["Security", "security"],
  ["Shopping", "shopping"],
  ["Social", "social"],
  ["Sports & Fitness", "sportsandfitness"],
  ["Test Data", "testdata"],
  ["Text Analysis", "textanalysis"],
  ["Tracking", "tracking"],
  ["Transportation", "transportation"],
  ["URL Shorteners", "urlshorteners"],
  ["Vehicle", "vehicle"],
  ["Video", "video"],
  ["Weather", "weather"],
];
